ASSIGNMENT-1 - priya sharma

Ques-1 Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
reversed=np.flip(arr)
print(reversed)

[5 4 3 2 1]


Ques-2 Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]]) arr2 = np.array([[1, 2], [3, 4]])

In [4]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
print(arr1==arr2)

[[ True  True]
 [ True  True]]


Ques-3 Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

In [5]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
ct_x=np.bincount(x)
print("frequency of each number:",ct_x)
mostfreq=np.argmax(ct_x)
print("most frequent number is:",mostfreq)
indices=np.where(x==mostfreq)[0]
print("indices of most freq number:",indices)

frequency of each number: [0 5 2 1 1 1]
most frequent number is: 1
indices of most freq number: [0 5 7 8 9]


In [6]:
y=np.array([1,1,1,2,3,4,2,4,3,3])
ct_y=np.bincount(y)
print("frequency of each number:",ct_y)
mostfreq_y=np.argmax(ct_y)
print("most frequent number is:",mostfreq_y)
indices_y=np.where(y==mostfreq_y)[0]
print("indices of most freq number:",indices_y)

frequency of each number: [0 3 2 3 2]
most frequent number is: 1
indices of most freq number: [0 1 2]


Ques-4 For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all element’s row-wise

iii. Sum of all element’s column-wise



In [7]:
gfg=np.matrix('[4,1,9; 12,3,1; 4,5,6]')
print(gfg)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]


In [8]:
sum_all_ele=np.sum(gfg)
print("total sum:",sum_all_ele)

total sum: 45


In [9]:
row_wise=np.sum(gfg,axis=1)
print("row wise sum:",row_wise)

row wise sum: [[14]
 [16]
 [15]]


In [10]:
column_wise=np.sum(gfg,axis=0)
print("column wise sum:",column_wise)

column wise sum: [[20  9 16]]
